version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=585675102017.dkr.ecr.us-east-1.amazonaws.com/nodejs-aws-sample
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo REPOSITORY_URI $REPOSITORY_URI
      - echo COMMIT_HASH $COMMIT_HASH
      - echo IMAGE_TAG $IMAGE_TAG
  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker build --target build -t $REPOSITORY_URI:latest .
        - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Generating Docker run file with current tag for deployment...
      - sed -i -e 's|TAG_NAME|'$TAG_NAME'|g' Dockerrun.aws.json
      - echo 'Generated Dockerrun.aws.json file:'
      - cat Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
  name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths